# Render Blueprint API
# https://render.com/docs/blueprint-spec

services:
  - type: web
    name: build-performance-app
    env: node
    plan: starter
    runtime: node
    buildCommand: NODE_ENV=development npm run install:all && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: build-performance-db
          property: connectionString

  - type: cron
    name: build-performance-scheduler
    env: node
    schedule: "0 0 * * *"  # Run daily at midnight
    buildCommand: NODE_ENV=development npm run install:all
    startCommand: cd server && npm run fetch-builds
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: build-performance-db
          property: connectionString
      # Provider API Keys - Add your actual API keys in the Render dashboard
      - key: RENDER_ENABLED
        value: "true"
      - key: RENDER_API_KEY
        value: ""  # Set this in the Render dashboard
      - key: VERCEL_ENABLED
        value: "false"
      - key: NETLIFY_ENABLED
        value: "false"
      - key: AWS_AMPLIFY_ENABLED
        value: "false"
      - key: GITHUB_PAGES_ENABLED
        value: "false"
    # Specify Node.js version
    nodeVersion: 18

databases:
  - name: build-performance-db
    plan: basic-4gb 