# Render Blueprint API
# https://render.com/docs/blueprint-spec

services:
  - type: web
    name: build-performance-app
    env: node
    plan: starter
    runtime: node
    buildCommand: npm install && npm run install:client && npm run install:server && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: build-performance-db
          property: connectionString
    # Specify Node.js version
    nodeVersion: 18.x

  - type: cron
    name: build-performance-scheduler
    env: node
    schedule: "0 0 * * *"  # Run daily at midnight
    buildCommand: npm install
    startCommand: node scripts/compare-providers.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_ENDPOINT
        value: https://build-performance-app.onrender.com/api/builds
      - key: DATABASE_URL
        fromDatabase:
          name: build-performance-db
          property: connectionString
    # Specify Node.js version
    nodeVersion: 18.x

databases:
  - name: build-performance-db
    plan: basic-4gb 