name: Manual GitHub Pages Deploy

on:
  workflow_dispatch:
    inputs:
      debug_mode:
        description: 'Run in debug mode'
        required: false
        default: false
        type: boolean

jobs:
  deploy_to_gh_pages:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'client/package-lock.json'
    
    # Cache client node_modules
    - name: Cache client dependencies
      uses: actions/cache@v3
      id: cache-client
      with:
        path: client/node_modules
        key: ${{ runner.os }}-node-client-${{ hashFiles('client/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-client-
    
    - name: Install gh-pages package
      run: npm install gh-pages --save-dev
    
    - name: Install client dependencies
      if: steps.cache-client.outputs.cache-hit != 'true'
      run: cd client && npm install
    
    # Note: We're skipping server-side code completely in this workflow,
    # so no linting or tests are needed
    
    - name: Show debug info
      if: ${{ github.event.inputs.debug_mode }}
      run: |
        echo "Current directory: $(pwd)"
        echo "Repository: ${{ github.repository }}"
        echo "Node version: $(node --version)"
        echo "NPM version: $(npm --version)"
        ls -la
        ls -la client
    
    - name: Build client
      env:
        CI: "false"  # Prevents warnings from being treated as errors
      run: cd client && npm run build
    
    # Cache build outputs to speed up future deployments
    - name: Cache build outputs
      uses: actions/cache@v3
      with:
        path: client/build
        key: ${{ runner.os }}-gh-pages-build-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-gh-pages-build-
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./client/build
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        commit_message: 'Deploy to GitHub Pages'
    
    - name: Deployment result
      run: |
        echo "=== GitHub Pages Deployment Summary ==="
        echo "Deployed at: $(date)"
        echo "Repository: ${{ github.repository }}"
        echo "Triggered by: ${{ github.actor }}"
        echo "Pages URL: https://$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]').github.io/$(echo ${{ github.event.repository.name }} | tr '[:upper:]' '[:lower:]')/" 